# Generated by Django 6.0.7 on 2026-07-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
