# Generated by Django 6.0.7 on 2026-07-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_department_employee_user_user_role_and_more'),
    ]

    operations = [
    ]
